### ISSUE TITLE
The restart time is too long.

### ISSUE THREAD

**Issue by justinchao740** [ThatTonybo/IdleStopStart#1]
Here's an example of a better implemented start-stop.
https://www.beamng.com/threads/etk-auto-stop.57663/
The start time for this mod is too long, causing the car to roll back and lurch forwards when driving off at the lights for example.
If you can change it to be more like the ETK auto-stop that I linked it would make this mod perfect.

**Comment by ThatTonybo** [comment]
I'll take a look into Arcanox's code to see if there's any improvements I can make; however my goal isn't to modify engine values for every vehicle, which it looks like theirs does for the ETK line-up.

**Comment by ThatTonybo** [comment]
Fixed/updated in 1.1
